apiVersion: v1
kind: Pod
metadata:
  name: ml-app-resources
  labels:
    app: ml-app
spec:
  containers:
    - image: mikhailmar/online_inference:v1
      name: ml-app
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "512Mi"
          cpu: "100m"
        limits:
          memory: "1Gi"
          cpu: "200m"
