apiVersion: v1
kind: Pod
metadata:
  name: ml-app-probes
  labels:
    app: ml-app
spec:
  containers:
    - image: mikhailmar/online_inference:v2
      name: ml-app
      ports:
        - containerPort: 8000
      args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 60; rm -f /tmp/healthy
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 20
        periodSeconds: 5
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initialDelaySeconds: 30
        periodSeconds: 10
