apiVersion: v1
kind: Pod
metadata:
  name: ml-app
  labels:
    app: ml-app
spec:
  containers:
    - image: mikhailmar/online_inference:v1
      name: ml-app
      ports:
        - containerPort: 8000
